[tool.poetry]
name = "sendgridemailer"
version = "0.1.0"
description = ""
authors = ["mptMachine <mptmessages@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
